name: chatbotui
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  chat_bubbles: ^1.6.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  bubble: 
  provider:
  #intl:
  animated_bottom_navigation_bar: ^0.3.3
  font_awesome_flutter: ^9.2.0
  page_transition: ^2.0.5
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0

  #Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^6.0.4
  #introduction_screen: ^3.1.12
  smooth_page_indicator: ^1.1.0

  # dependencies of weather widget
  http: ^1.2.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  lottie: ^3.0.0
  intl: 0.19.0 

  #scan page
  image_cropper: ^5.0.1
  image_picker: ^0.8.5+3
  permission_handler: ^10.2.0

  #splash screen
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.13.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/TeaHub_icon.jpg"
  

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

assets:
  - assets/services.json
  - assets/default.jpg
  - assets/robot.jpg
  - assets/
  - assets/images/
  - assets/images/bgimag.png
  - assets/images/rectangle-8.png
  - assets/images/headsetsvgrepocom.png
  - assets/images/play-buttonsvgrepocom.png
  - assets/images/vector-8MD.png
  - assets/images/vector-SuD.png
  - assets/images/vector-pGX.png
  - assets/images/vector-UWj.png
  - assets/images/snap_tips imgs/
  - assets/images/treatment_imgs/

  # assets of weather widget
  - assets/weather_animation/loading.json
  - assets/weather_animation/clear_day.json
  - assets/weather_animation/clear_night.json
  - assets/weather_animation/cloudy_day.json
  - assets/weather_animation/cloudy_night.json
  - assets/weather_animation/mist_day.json
  - assets/weather_animation/mist_night.json
  - assets/weather_animation/partly_cloudy_day.json
  - assets/weather_animation/partly_cloudy_night.json
  - assets/weather_animation/partly_rain_day.json
  - assets/weather_animation/partly_rain_night.json
  - assets/weather_animation/rain_day.json
  - assets/weather_animation/rain_night.json
  - assets/weather_animation/thunder_strom_day.json
  - assets/weather_animation/thunder_storm_night.json

  #assets of user profile
  - assets/user_profile/images/rectangle-51.png
  - assets/user_profile/images/top.png
  - assets/user_profile/images/rectangle-6.png
  - assets/user_profile/images/group-62.png
  - assets/user_profile/images/line-business-profile-line.png
  - assets/user_profile/images/line-media-notification-3-line.png
  - assets/user_profile/images/auto-group-oclv.png
  - assets/user_profile/images/line-user-contacts-line.png
  - assets/user_profile/images/line-communication-chat-quote-line.png
  - assets/user_profile/images/line-system-lock-2-line.png
  - assets/user_profile/images/float-btn-5hq.png
  - assets/user_profile/images/bg-ysV.png
  - assets/user_profile/images/scansvgrepocom-N6T.png

  #assets of main interface
  - assets/page-1/images/setting.png
  - assets/page-1/images/stylelinear.png
  - assets/page-1/images/vector.png
  - assets/page-1/images/book-albumsvgrepocom.png
  - assets/page-1/images/scansvgrepocom.png
  - assets/page-1/images/vector-AHS.png
  - assets/page-1/images/auto-group-ucn8.png
  - assets/page-1/images/vector-8vg.png
  - assets/page-1/images/assistant.png
  - assets/page-1/images/vector-ax4.png
  - assets/page-1/images/peperomia-obtusfolia.png

    #splash screen
  - assets/splashscreen/Animation.json
  - assets/splashscreen/loader.json

    #edit profile page
  - assets/editProfileImages

    #introsplash
  - assets/introsplash/tree.png
  - assets/introsplash/chatbot.png
  - assets/introsplash/teaprofile.png

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
uses-material-design: true
fonts: 
    - family: Poppins
      fonts: 
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
    - family: Red Hat Text
      fonts: 
        - asset: assets/fonts/RedHatTextRomanLight.ttf
          weight: 300
    - family: Roboto
      fonts: 
        - asset: assets/fonts/RobotoRegular.ttf
          weight: 400
        - asset: assets/fonts/RobotoRomanMedium.ttf
          weight: 500


  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
