// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRQt0-LRU434YbofXgRRnLwz3M5r0jOko',
    appId: '1:1015273066077:web:a04102770cd8c1892c07b4',
    messagingSenderId: '1015273066077',
    projectId: 'teahub-user-authentication',
    authDomain: 'teahub-user-authentication.firebaseapp.com',
    storageBucket: 'teahub-user-authentication.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApGuilr0-2FnbAMW4H9Kjwa8gLa9biSlg',
    appId: '1:1015273066077:android:1f483103884e65f22c07b4',
    messagingSenderId: '1015273066077',
    projectId: 'teahub-user-authentication',
    storageBucket: 'teahub-user-authentication.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmP5dJK4sd_DuCHWJshFSjD4qu2cTh3UU',
    appId: '1:1015273066077:ios:43ddf369307437d42c07b4',
    messagingSenderId: '1015273066077',
    projectId: 'teahub-user-authentication',
    storageBucket: 'teahub-user-authentication.appspot.com',
    iosClientId: '1015273066077-7cfcp445csabf493lmmp5u37cjscn0g9.apps.googleusercontent.com',
    iosBundleId: 'com.example.teahub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmP5dJK4sd_DuCHWJshFSjD4qu2cTh3UU',
    appId: '1:1015273066077:ios:a05e55eb540973902c07b4',
    messagingSenderId: '1015273066077',
    projectId: 'teahub-user-authentication',
    storageBucket: 'teahub-user-authentication.appspot.com',
    iosClientId: '1015273066077-h0rfk9mu0sdd1u57flkm16lr3fjjje6h.apps.googleusercontent.com',
    iosBundleId: 'com.example.teahub.RunnerTests',
  );
}
