name: AndroidBuild
on: 
    pull_request:
        branches: [ main ]
    push:
        branches: [ main ]

jobs:
    build:
        runs-on : ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4.1.2

            - name:  Setup Java JDK
              uses: actions/setup-java@v4.2.1
              with:
                java-version: '17'
                distribution: 'adopt'

            - name: Grant execute permission for gradlew
              run: chmod +x ./android/gradlew

            - name: Build With Gradle
              run: cd android && ./gradlew build

            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v4.3.1
              with:
                name: TeaHub.apk
                path: app/build/outputs/apk/TeaHub-debug.apk
                
            
            
    
    

         






